"""add password

Revision ID: b5475dc337a5
Revises: 490d8d0b782f
Create Date: 2026-05-29 16:06:46.467475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5475dc337a5'
down_revision: Union[str, Sequence[str], None] = '490d8d0b782f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.execute("UPDATE employees SET password_hash='placeholder' WHERE password_hash IS NULL")
    op.alter_column("employees","password_hash",nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'password_hash')
    # ### end Alembic commands ###
