"""add roles

Revision ID: d23c98db0a89
Revises: 2cb6af2aa19a
Create Date: 2026-06-01 14:18:31.131686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23c98db0a89'
down_revision: Union[str, Sequence[str], None] = '2cb6af2aa19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
_ROLE_ENUM=sa.Enum("UI","UX","Developer","HR",name="employeerole")

def upgrade() -> None:
    """Upgrade schema."""
    _ROLE_ENUM.create(op.get_bind(),checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('role',_ROLE_ENUM, nullable=False, server_default='Developer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'role')
    # ### end Alembic commands ###
